# This script assumes that complete datasets (complete_data_*.csv)
# have already been generated (see 01_simulate_complete_datasets.R)

# Load necessary libraries
library(dplyr)
library(lme4)
library(rblimp)
library(broom.mixed)
# Set path to your local Blimp installation
blimp_path <- "C:/Program Files/Blimp/blimp.exe"
rblimp::set_blimp(blimp_path)
# Set your working directory here
# setwd("path/to/your/simulation/folder")

# -------------------------------------------------------------------------
# 1. SETUP
# -------------------------------------------------------------------------
n_sims <- 1000

backup_file <- "simulation_results_master.csv"
# Remove existing file so results are not appended to old runs
if (file.exists(backup_file)) file.remove(backup_file)

# -------------------------------------------------------------------------
# Induce missingness and run models
# -------------------------------------------------------------------------
for (i in seq_len(n_sims)) {
  
  # A. Read the complete data generated by Blimp
  file_name <- paste0("complete_data_", i, ".csv")
  dat <- read.csv(file_name)
  
  # B. Induce MAR Missingness
  dat <- dat %>%
    mutate(
      prob_missing = plogis(-0.5 + 2.5 * aux),
      is_missing = rbinom(n(), 1, prob_missing),
      y_mar = ifelse(is_missing == 1, NA, y),
      x_mar = ifelse(is_missing == 1, NA, x)
    )
  
  # Calculate missing rate for the console dashboard
  current_miss_rate <- mean(dat$is_missing)
  
  # C. Calculate Pre-Centered Variables 
  dat <- dat %>%
    group_by(id2) %>%
    mutate(
      x_mean_true = mean(x),
      x_cwc_true  = x - x_mean_true,
      x_mean_biased = mean(x_mar, na.rm = TRUE),
      x_cwc_biased  = x_mar - x_mean_biased
    ) %>%
    ungroup()
  
  # -----------------------------------------------------------------------
  # ESTIMATE THE 6 MODELS
  # -----------------------------------------------------------------------
  m1 <- lmer(y ~ x_cwc_true + x_mean_true + (1 | id2), data = dat)
  
  m2 <- rblimp(data = dat, clusterid = "id2", center = "groupmean = x", 
               model = "y ~ x x.mean;", seed = 12345+ i)
  
  m3 <- lmer(y_mar ~ x_cwc_biased + x_mean_biased + (1 | id2), data = dat)
  
  m4 <- rblimp(data = dat, clusterid = "id2", center = "groupmean = x_mar", 
               model = "y_mar ~ x_mar x_mar.mean;", seed = 12345+ i)
  
  m5 <- rblimp(data = dat, clusterid = "id2", 
               model = "y_mar ~ x_cwc_biased x_mean_biased;
                        aux ~ y_mar x_cwc_biased x_mean_biased;", seed = 12345+ i)
  
  m6 <- rblimp(data = dat, clusterid = "id2", center = "groupmean = x_mar", 
               model = "y_mar ~ x_mar x_mar.mean; 
                        aux ~ y_mar y_mar.mean x_mar x_mar.mean;", seed = 12345+ i)
  
  # -----------------------------------------------------------------------
  # EXTRACT PARAMETERS
  # -----------------------------------------------------------------------
  # Model labels correspond to simulation conditions:
  # lmer_complete = complete data benchmark (frequentist estimation using lmer)
  # complete_blimp = complete data benchmark (Bayesian estimation using Blimp)
  # naive_no_aux = incomplete data without auxiliary variable (lmer)
  # lmc_no_aux = incomplete data without auxiliary variable (Blimp with latent centering)
  # omc_with_aux = observed mean centering with auxiliary variable included (Blimp)
  # lmc_with_aux = latent mean centering with auxiliary variable included (Blimp)
  
  m1_sum <- summary(m1)$coefficients
  m3_sum <- summary(m3)$coefficients
  m1_vc <- as.data.frame(VarCorr(m1))
  m3_vc <- as.data.frame(VarCorr(m3))
  
  m1_bw_cov <- ifelse(0.4 > (m1_sum["x_cwc_true", "Estimate"] - 1.96 * m1_sum["x_cwc_true", "Std. Error"]) & 
                        0.4 < (m1_sum["x_cwc_true", "Estimate"] + 1.96 * m1_sum["x_cwc_true", "Std. Error"]), 1, 0)
  m1_bb_cov <- ifelse(0.6 > (m1_sum["x_mean_true", "Estimate"] - 1.96 * m1_sum["x_mean_true", "Std. Error"]) & 
                        0.6 < (m1_sum["x_mean_true", "Estimate"] + 1.96 * m1_sum["x_mean_true", "Std. Error"]), 1, 0)
  m3_bw_cov <- ifelse(0.4 > (m3_sum["x_cwc_biased", "Estimate"] - 1.96 * m3_sum["x_cwc_biased", "Std. Error"]) & 
                        0.4 < (m3_sum["x_cwc_biased", "Estimate"] + 1.96 * m3_sum["x_cwc_biased", "Std. Error"]), 1, 0)
  m3_bb_cov <- ifelse(0.6 > (m3_sum["x_mean_biased", "Estimate"] - 1.96 * m3_sum["x_mean_biased", "Std. Error"]) & 
                        0.6 < (m3_sum["x_mean_biased", "Estimate"] + 1.96 * m3_sum["x_mean_biased", "Std. Error"]), 1, 0)
  
  rblimp_cov <- function(model, param, truth) {
    ifelse(truth > model@estimates[param, "2.5%"] & truth < model@estimates[param, "97.5%"], 1, 0)
  }
  
  iter_results <- data.frame(
    sim_id = i,
    model_type = c("1_lmer_complete", "2_blimp_complete", "3_lmer_naive", 
                   "4_blimp_lmc_noaux", "5_blimp_omc_aux", "6_blimp_rescue"),
    b_0_est = c(m1_sum["(Intercept)", "Estimate"], m2@estimates["y ~ Intercept", "Estimate"],
                m3_sum["(Intercept)", "Estimate"], m4@estimates["y_mar ~ Intercept", "Estimate"],
                m5@estimates["y_mar ~ Intercept", "Estimate"], m6@estimates["y_mar ~ Intercept", "Estimate"]),
    b_w_est = c(m1_sum["x_cwc_true", "Estimate"], m2@estimates["y ~ x", "Estimate"],             
                m3_sum["x_cwc_biased", "Estimate"], m4@estimates["y_mar ~ x_mar", "Estimate"],
                m5@estimates["y_mar ~ x_cwc_biased", "Estimate"], m6@estimates["y_mar ~ x_mar", "Estimate"]),
    b_b_est = c(m1_sum["x_mean_true", "Estimate"], m2@estimates["y ~ x.mean[id2]", "Estimate"],        
                m3_sum["x_mean_biased", "Estimate"], m4@estimates["y_mar ~ x_mar.mean[id2]", "Estimate"],
                m5@estimates["y_mar ~ x_mean_biased", "Estimate"], m6@estimates["y_mar ~ x_mar.mean[id2]", "Estimate"]),
    cov_b_w = c(m1_bw_cov, rblimp_cov(m2, "y ~ x", 0.4), m3_bw_cov, rblimp_cov(m4, "y_mar ~ x_mar", 0.4),
                rblimp_cov(m5, "y_mar ~ x_cwc_biased", 0.4), rblimp_cov(m6, "y_mar ~ x_mar", 0.4)),
    cov_b_b = c(m1_bb_cov, rblimp_cov(m2, "y ~ x.mean[id2]", 0.6), m3_bb_cov, rblimp_cov(m4, "y_mar ~ x_mar.mean[id2]", 0.6),
                rblimp_cov(m5, "y_mar ~ x_mean_biased", 0.6), rblimp_cov(m6, "y_mar ~ x_mar.mean[id2]", 0.6)),
    var_u0_est = c(m1_vc[m1_vc$grp == "id2", "vcov"], m2@estimates["y level-2 intercept variance", "Estimate"],
                   m3_vc[m3_vc$grp == "id2", "vcov"], m4@estimates["y_mar level-2 intercept variance", "Estimate"],
                   m5@estimates["y_mar level-2 intercept variance", "Estimate"], m6@estimates["y_mar level-2 intercept variance", "Estimate"]),
    var_e_est = c(m1_vc[m1_vc$grp == "Residual", "vcov"], m2@estimates["y residual variance", "Estimate"],
                  m3_vc[m3_vc$grp == "Residual", "vcov"], m4@estimates["y_mar residual variance", "Estimate"],
                  m5@estimates["y_mar residual variance", "Estimate"], m6@estimates["y_mar residual variance", "Estimate"])
  )
  
  # -----------------------------------------------------------------------
  # CLEANUP SAVED FILES
  # -----------------------------------------------------------------------

  if (!file.exists(backup_file)) {
    write.csv(iter_results, backup_file, row.names = FALSE)
  } else {
    write.table(iter_results, backup_file, sep = ",", append = TRUE, 
                col.names = FALSE, row.names = FALSE)
  }
  
  # Clean up Blimp temporary files created during estimation
  local_temp <- list.files(pattern = "\\.(blimp-out|imp|dat)$")
  if(length(local_temp) > 0) file.remove(local_temp)
  
  # Optional: clean Blimp files from R's temp directory
  blimp_temp <- list.files(
    path = tempdir(),
    pattern = "\\.(blimp-out|imp|dat)$",
    full.names = TRUE
  )
  if (length(blimp_temp) > 0) file.remove(blimp_temp)
  
  # Print progress to console immediately
  if (i %% 10 == 0) {
    cat("Completed simulation:", i, " | Missing rate:", round(current_miss_rate * 100, 1), "%\n")
    flush.console()
  }
}

# -------------------------------------------------------------------------
# 6. SUMMARIZE RESULTS
# -------------------------------------------------------------------------
# Load the ENTIRE master file 
final_results <- read.csv("simulation_results_master.csv")

summary_table <- final_results %>%
  group_by(model_type) %>%
  summarize(
    b_w_mean = mean(b_w_est),
    b_w_abs_bias = mean(b_w_est) - 0.4,
    b_w_emp_se = sd(b_w_est),
    b_w_std_bias = (mean(b_w_est) - 0.4) / sd(b_w_est),
    b_w_coverage = mean(cov_b_w, na.rm = TRUE),
    
    b_b_mean = mean(b_b_est),
    b_b_abs_bias = mean(b_b_est) - 0.6,
    b_b_emp_se = sd(b_b_est),
    b_b_std_bias = (mean(b_b_est) - 0.6) / sd(b_b_est),
    b_b_coverage = mean(cov_b_b, na.rm = TRUE),
    
    var_u0_mean = mean(var_u0_est),
    var_u0_abs_bias = mean(var_u0_est) - 1.0,
    var_u0_std_bias = (mean(var_u0_est) - 1.0) / sd(var_u0_est),
    
    var_e_mean = mean(var_e_est),
    var_e_abs_bias = mean(var_e_est) - 1.0,
    var_e_std_bias = (mean(var_e_est) - 1.0) / sd(var_e_est)
  ) %>%
  mutate(across(where(is.numeric), ~round(.x, 3)))

print(t(summary_table))
write.csv(summary_table, "simulation_summary_table.csv", row.names = FALSE)
